---
- name: Update Netflow cache
  hosts: all
  connection: network_cli
  become: yes
  vars:
    cache_size: 12288
    interface_monitor_name: TEST_NETFLOW_MONITOR
    save_to_startup: true
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
        gather_subset: all

    - name: Check current cache size
      cisco.ios.ios_command:
        commands: show flow monitor {{ interface_monitor_name }} statistics | in Cache size
      register: flow_cache_output

    - set_fact:
        current_cache_size: "{{ flow_cache_output.stdout[0] | regex_search('(\\d+)', '\\1') | first }}"

    - name: Update cache setting if required
      block:
        - name: Loop over all interfaces for netflow input
          cisco.ios.ios_command:
            commands: show running-config interface {{ item.key }} | in {{ interface_monitor_name }}
          loop: "{{ ansible_net_interfaces | dict2items }}"
          register: running_interface_flow_config

        - name: Group interfaces and input/output lines
          set_fact:
            interface_monitor_commands: "{{ interface_monitor_commands | default([]) }} + [ {% for command in item.stdout_lines[0] %}{'interface_name': '{{ item.item.key }}', 'netflow_command': '{{ command }}'}{{ ',' if not loop.last else '' }}{% endfor %} ]"
          when: item.stdout_lines[0][0] | length > 0
          loop: "{{ running_interface_flow_config.results }}"

        - name: Display all interface and config pairs
          debug:
            var: interface_monitor_commands

        - name: No all interface_monitor_commands
          cisco.ios.ios_config:
            lines: no {{ item.netflow_command }}
            parents: interface {{ item.interface_name }}
          loop: "{{ interface_monitor_commands }}"

        - name: Update cache size
          cisco.ios.ios_config:
            lines: cache entries {{ cache_size }}
            parents: flow monitor {{ interface_monitor_name }}

      always:
        - name: Restore all interface_monitor_commands
          cisco.ios.ios_config:
            lines: "{{ item.netflow_command }}"
            parents: interface {{ item.interface_name }}
          loop: "{{ interface_monitor_commands }}"

        - name: Save running to startup
          cisco.ios.ios_config:
            save_when: always
          when: save_to_startup
      when: (current_cache_size | int) != (cache_size | int)
